# Generated by Django 5.2.6 on 2025-10-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_message_moodentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
